### ISSUE TITLE
Document how to make the device detectable by YARP

### ISSUE THREAD

**Issue by xEnVrE** [robotology/yarp-device-realsense2#21]
I noticed that the documentation for building the device suggests to `make install` after the actual build process.

However, I think that this might be incomplete given that the default `CMAKE_INSTALL_PREFIX` is not necessarily the one compatible with the installation path of `YARP`, i.e. such that `YARP_DATA_DIRS` contains a path pointing to the `ini` file of the device.

In specific contexts, e.g. when `YARP` was installed as part of the `robotology-supebuild`, one could also (even if not totally advisable) use `<robotology_superbuild_src_dir>/build/install` as `CMAKE_INSTALL_PREFIX`.

Do you think it is possible to add some related documentation?

**Comment by traversaro** [comment]
Sure! If you think worth, you can also take inspiraction or copy&paste some parts from https://github.com/robotology/forcetorque-yarp-devices#step-by-step-installation .

**Comment by xEnVrE** [comment]
Thank you, addressing this in #22
