### ISSUE TITLE
Update the list of supported cameras

### ISSUE THREAD

**Issue by xEnVrE** [robotology/yarp-device-realsense2#38]
The list of supported cameras in the `README.md` seems not up-to-date:

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/README.md?plain=1#L8-L11

as far as I know, the yarp device works also with:
- `Realsense D41x` (tested personally)
- `RealSense D45x` (used on ergoCub)

Should I open a PR to update the file?

**Comment by traversaro** [comment]
> Should I open a PR to update the file?

Yes, thanks!

**Comment by xEnVrE** [comment]
Ok, I will do it after #39, so that we can also add the `D405` to the list.
