### ISSUE TITLE
Support the RealSense D405

### ISSUE THREAD

**Issue by xEnVrE** [robotology/yarp-device-realsense2#39]
At the moment the `yarp-device-realsense2` does not support the short-range RealSense D405 camera.

The main reason is that this camera only exposes a depth sensor, i.e. in the following for cycle

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2Driver.cpp#L599-L612

only the depth sensor pointer `m_depth_sensor` gets initialized (while for the D415, D435 and D455 also the `m_color_sensor` gets initialized).

Despite the fact that it only has a depth sensor, in terms of the internal Intel device enumeration, Intel still provides a proper RGB stream - i.e. it is fully supported for this camera.

At the moment, the driver calls the following method eventually:

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2Driver.cpp#L638

which fails at this line

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2Driver.cpp#L757

because

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2Driver.cpp#L865-L868

`m_color_sensor` is not initialized.

Nonetheless, the code is made in a way such that, **if we could make the initialization of the RGB paramters part optional**, the initialization completes successfully (as there is no need for setting the resolution parameter for the RGB device, as it does not exist!).

I tried commenting the part - that we should make optional - and I got this:

![image](https://user-images.githubusercontent.com/6014499/225067647-b8b66658-87eb-4a1f-aa6b-95632b78b0bc.png)

While the RGB part is ok, the depth is clearly wrong as we get invalid values for small box on the table.

I know that it is wrong also because I have a tiny C++ executable that I use for testing RealSense cameras which produce this totally different result:

![image](https://user-images.githubusercontent.com/6014499/225068326-fa2d6e6e-0636-4fd1-bbf1-700d25077afa.png)

which makes more sense as the D405 can produce reasonable depth maps for object as near as 7 cm (although I am not sure about the color being so different!).

We should better investigate what the code does within the YARP device and understand if we are making any configuration that is maybe not compatible with the D405.

cc @Arya07 @fedeceola @randaz81 @Nicogene

**Comment by xEnVrE** [comment]
After further investigation, I discovered that:

- the D405 uses a different value for scaling the raw depth values to the actual ones (in meters) than that used in D415/D435 cameras
- the standalone C++ executable used for testing was using the wrong scale value (0.001 while it should be 0.0001)

After this change, the output of the test executable is the same obtained using the YARP device, which seems wrong according to the output of the portmonitor.

Then might it just be that the portmonitor is clipping out too near values?

I also made a test with the same scene and compared with the `realsense-viewer`:

### realsense-viewer

![image](https://user-images.githubusercontent.com/6014499/225092275-2621968f-fcbd-4c69-93c9-409848b133d4.png)

### YARP device

![image](https://user-images.githubusercontent.com/6014499/225092677-3d919383-fc26-4955-815c-25d3c68ccdeb.png)

**Comment by xEnVrE** [comment]
After changing that, we now get the expected depth map in the viewer:

![image](https://user-images.githubusercontent.com/6014499/225094676-eb86410d-c751-4b0e-8355-43f19c392416.png)

To recap, I think we could get the D405 up and running with the YARP device by making the initialization of the RGB parameters optional.

**Comment by traversaro** [comment]
> To recap, I think we could get the D405 up and running with the YARP device by making the initialization of the RGB parameters optional, as described in [#39 (comment)](https://github.com/robotology/yarp-device-realsense2/issues/39#issue-1623818282).

Great, feel free to open a PR, thanks!

**Comment by xEnVrE** [comment]
A draft PR has been opened in #40.

**Comment by xEnVrE** [comment]
Last week @fedeceola made some tests with the `D405` mounted on the robot. He used the software with the changes from the above PR.

He noticed that there is something wrong with the RGB/Depth alignment:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/6014499/231429818-3bed0cf4-3ded-485f-863e-e04548120c4b.png)

We are going to further investigate this and update the PR accordingly.

**Comment by xEnVrE** [comment]
We also checked the alignment on the images from the `realsense-viewer`. 

<img src="https://user-images.githubusercontent.com/6014499/231430225-bf569a66-c938-4986-86ff-241dab1d5774.png" height=500/>

This works as expected, as can be seen by superimposing the images:

![image](https://user-images.githubusercontent.com/6014499/231431952-afb55d93-7959-4a14-a2f5-86a2ac2a920c.png)

**Comment by Nicogene** [comment]
Hi @xEnVrE, this happens one of the two sensor uses a resolution that is not native.

For this reason, there is the parameter `alignmentFrame` that should fix the problem. I don't remember if changes also the resolution.

**Comment by xEnVrE** [comment]
Hi @Nicogene, the alignment has been activated. My thought was that it is not working properly with the `D405` camera. It might depend on the change that I made in the PR.

**Comment by xEnVrE** [comment]
Thanks for the suggestion @Nicogene.

Yep, we could also try to understand which mode is used inside the `realsense-viewer` for the `D405` when the alignment is enabled.

I always assumed that we wanted to align against the `RGB` frame as the depth has holes which would result in an aligned RGB images with holes as well.

**Comment by xEnVrE** [comment]
>  we might support completely disabling the alignment within this device

This is already possible by using the option `<alignmentFrame>None<\alignmentFrame>`. I tested it with this option and now the alignment is as expected:

![image](https://github.com/robotology/yarp-device-realsense2/assets/6014499/cbdb3822-34f2-43bd-9e8a-6cb5416304c4)

**Comment by xEnVrE** [comment]
Given that `alignmentFrame=None` is already supported in this device, I would just document in the `README.md` how to configure cameras with special "features" like the D405. What do you think @Nicogene?
